repository:
  default_branch: main

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: []
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        require_last_push_approval: false
      restrictions: null
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      block_creations: true
      required_conversation_resolution: true
      required_signatures: true
      lock_branch: false
      allow_fork_pushes: false
      allow_fork_pr_pushes: true
